#!/bin/bash

# https://www.youtube.com/watch?v=X3Pr5VATOyA
# https://www.youtube.com/watch?v=7VAI73roXaY&t=176s

sudo apt-get update
sudo apt install nginx

sudo mkdir /etc/nginx/ssl
sudo chmod 700 /etc/nginx/ssl

# Generates self signed certificate which similar to CA-signed certificates
# Only drawback being it will give the user warning that the cert is not trusted
# sudo openssl req -newkey rsa:2048 -keyout /etc/nginx/ssl/example.key -x509 -nodes -days 365 -out /etc/nginx/ssl/example.crt
sudo openssl req -newkey rsa:2048 -keyout /etc/nginx/ssl/example.key -x509 -nodes -days 365 -out /etc/nginx/ssl/example.crt

# Country Name (2 letter code) [AU]:IN
# State or Province Name (full name) [Some-State]:Delhi
# Locality Name (eg, city) []:New Delhi
# Organization Name (eg, company) [Internet Widgits Pty Ltd]:NGINX, Inc
# Organizational Unit Name (eg, section) []:NGINX
# Common Name (e.g. server FQDN or YOUR name) []:www.example.com
# Email Address []:ashishgaurp91@gmail.com

cd /etc/nginx/conf.d/
sudo vim www.example.org.conf

sudo nginx -s reload
